name: Attach Release Asset

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  build-on-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --release

      - name: Build (x86_64-unknown-linux-musl)
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --release --target x86_64-unknown-linux-musl

      - name: compress
        run: |
          tar -czf target/release/ubuntu-latest.tar.gz target/release/chiritori
          tar -czf target/x86_64-unknown-linux-musl/release/x86_64-unknown-linux-musl.tar.gz target/x86_64-unknown-linux-musl/release/chiritori

      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-latest-binary
          path: |
            target/release/ubuntu-latest.tar.gz
            target/x86_64-unknown-linux-musl/release/x86_64-unknown-linux-musl.tar.gz

  build-on-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --release

      - name: compress
        run: |
          tar -czf target/release/macos-latest.tar.gz target/release/chiritori

      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: macos-latest-binary
          path: |
            target/release/macos-latest.tar.gz

  release:
    needs:
      - build-on-ubuntu
      - build-on-macos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artifacts (ubuntu-latest-binary)
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-binary

      - name: Download Artifacts (macos-latest-binary)
        uses: actions/download-artifact@v4
        with:
          name: macos-latest-binary

      - name: Create Release (nightly)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly
          draft: true
          prerelease: true
          files: |
            release/ubuntu-latest.tar.gz
            x86_64-unknown-linux-musl/release/x86_64-unknown-linux-musl.tar.gz
            macos-latest.tar.gz

      - name: Create Release(Release)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ github.ref }}
          files: |
            release/ubuntu-latest.tar.gz
            x86_64-unknown-linux-musl/release/x86_64-unknown-linux-musl.tar.gz
            macos-latest.tar.gz
